In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score, classification_report, confusion_matrix , f1_score

# Load dataset
df = pd.read_csv("Personalized_Diet_RecommendationsFE.csv")

# Define features
features = [
    'Daily_Steps', 'Cholesterol_Level', 'Protein_Intake', 'Fat_Intake',
    'Carbohydrate_Intake', 'Blood_Pressure_Systolic', 'Blood_Sugar_Level',
    'Age', 'Sleep_Hours', 'Dietary_Habits_Vegan', 'Food_Aversions_Salty',
    'Macro_Average', 'Health_Score'
]
X = df[features]
y_true = df['Recommended_Meal_Plan']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y_true, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Predict meal plans based on thresholds
def assign_meal_plan(row):
    protein = row['Protein_Intake']
    fat = row['Fat_Intake']
    carbs = row['Carbohydrate_Intake']
    if protein > np.percentile(df['Protein_Intake'], 75):
        return 0  # High-Protein
    elif fat < np.percentile(df['Fat_Intake'], 25):
        return 2  # Low-Fat
    elif carbs < np.percentile(df['Carbohydrate_Intake'], 25):
        return 3  # Low-Carb
    else:
        return 1  # Balanced

# Apply to test set
X_test_df = pd.DataFrame(X_test, columns=features)
y_pred = X_test_df.apply(assign_meal_plan, axis=1)

# Evaluate
balanced_acc = balanced_accuracy_score(y_test, y_pred)
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Threshold-Based Balanced Accuracy:", balanced_acc)
print("Macro F1-Score:", macro_f1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Threshold-Based Balanced Accuracy: 0.25
Macro F1-Score: 0.10998439937597504

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       248
           1       0.00      0.00      0.00       259
           2       0.28      1.00      0.44       282
           3       0.00      0.00      0.00       211

    accuracy                           0.28      1000
   macro avg       0.07      0.25      0.11      1000
weighted avg       0.08      0.28      0.12      1000


Confusion Matrix:
[[  0   0 248   0]
 [  0   0 259   0]
 [  0   0 282   0]
 [  0   0 211   0]]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
